### ISSUE TITLE
Login, User 도메인 분리

### ISSUE THREAD

**Issue by hyungzin0309** [yomankum-project/backWeb#20]
Desc
- Login 과 User 도메인을 분리하여 구분한다.

Todo
- Login 과 User 도메인을 분리

**Comment by h0l1da2** [comment]
2024-01-21
제가 이슈 해결 맡았습니다!

**Comment by h0l1da2** [comment]
2024-01-27
로그인 관련 기능을 유저에 포함시켰습니다.
